Add Classes Page
deadlocked247/sl-time-tracking pull request #8
Opened 2016-11-15 16:24 UTC by kosigz

2016-11-15 16:26 UTC, jackfrys submitted a review, later dismissed
wow good job

2016-11-15 16:28 UTC, deadlocked247 requested changes
This code effects the redux layer, just make sure you fix that and add some basic tests because "test driven development"

2016-11-15 16:28 UTC, deadlocked247 commented on src/App.js
> +  ADD_CLASSES: '/add-classes',
make this `/classes/add`

2016-11-15 16:28 UTC, deadlocked247 commented on src/pages/Classes/AddClasses.js
> +  static courseToProjects = {
can we put all this in an outside `.stub` file and import it? This will get really confusing once we get api calls

2016-11-15 16:28 UTC, deadlocked247 commented on src/pages/Classes/AddClasses.js
> +      <br/><br/>
use padding, don't use `br`

2016-11-15 16:28 UTC, deadlocked247 commented on src/pages/Classes/AddClasses.js
> +      <div className="ui container">
dont use classes, use react semantic components e.g. `<Container>` here

2016-11-15 16:28 UTC, deadlocked247 commented on src/pages/Home/Home.js
> +    classes: [{ name: 'CS 4500: Software Development' }, { name: 'ANTH 5513: Ancient Greek History' }],
This is going to change a lot in the redux layer, so nothing will be matching anymore from home page -> enter time page

2016-11-15 16:28 UTC, deadlocked247 commented on src/pages/Home/Home.js
> +    classes: [{ name: 'CS 4500: Software Development' }, { name: 'ANTH 5513: Ancient Greek History' }],
look at `/redux/reducers/...`

2016-11-29 20:48 UTC, deadlocked247 commented
LGTM

2016-11-29 20:48 UTC, deadlocked247 approved these changes

2016-11-30 02:16 UTC, merged